builds:
  - binary: pgdash
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -extldflags "-static"
    env:
      - CGO_ENABLED=0
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
    wrap_in_directory: true
release:
  draft: true
  github:
    owner: rapidloop
    name: pgdash
  name_template: 'Release {{.Version}}'
checksum:

